# Use an official Python image as the base image
FROM python:3.10-slim

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    curl \
    gnupg \
    git \
    && rm -rf /var/lib/apt/lists/*

# Add Google Chrome's official repository to the sources list
RUN curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list

# Install Google Chrome
RUN apt-get update && apt-get install -y google-chrome-stable \
    && rm -rf /var/lib/apt/lists/*

# Clone the PyAI Git repository
RUN git clone https://github.com/brandondjango/PyAI.git /app/PyAI

# Set the working directory to the project root
WORKDIR /app/PyAI

# Download the ChromeDriver to the project root
RUN wget -O chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.84/linux64/chrome-linux64.zip \
    && unzip chrome-linux64.zip -d ./ \
    && rm chrome-linux64.zip

# Optionally, install Python dependencies (if required by the PyAI project)
RUN pip install -r requirements.txt

# Set the entrypoint to bash
CMD ["bash"]