chat_gpt_key: !!binary |
  Z0FBQUFBQm13ekZSUlhmV182anEyQ2REYV9FY19kR20zQnNSSjRlVXgtS3hHMzVObF9IaDJtY2dr
  LWg0cF9hbExOVHhPV0c4UFd2RWhSVUl3bkptY0tyWGVfbTdma2lkM0tnWXlhdE5oWEJ2OXFXeC1l
  TGM0V1pMaEhteGEySkdFWUpBRUFjS1FkbTQzRUJtTm1taVNWWk9mempzTHRHYUNyajV6RkNLQ0d1
  NWJ4UFJ4aTZoVzM3UFNaSnpKVDl2a1dnN1VYVW9Sa0xLSnNraFFIQlBwR0Z5aEhwNEpSWlBnWXox
  Q1dMM3VZdXk0Qkd3NHZ3TGw2VmoyODFCUVY5Si1lVzJiSTUxMmhQcw==
